version: '3'

networks:
  php:

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_php
    ports: 
      - "40:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - php

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_php
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - php


  # mysql:
  #   image: joao159159/mysql-pers:latest
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: cfa
  #     MYSQL_USER: cfa
  #     MYSQL_PASSWORD: 159159
  #     MYSQL_ROOT_PASSWORD: 159159
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - "3308:3306"
  #   networks: 
  #     - php