version: '3'

networks:
  php:

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_php
    ports: 
      - "41:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - php

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_php
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9004:9004"
    networks: 
      - php